### PR TITLE
Add support for export ... from syntax

### PR DESCRIPTION
**Pull request by olalonde**

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
@olalonde Thanks so much for contributing! Awesome work and great catch. 

I just published a patch release. Feel free to bring that to Madge.

**Comment by olalonde** [comment]
Thanks 😄

**Comment by olalonde** [comment]
I'm trying to use this in madge but for some reason it doesn't seem to work in my test....

https://github.com/pahen/madge/compare/master...olalonde:reexport

If you have any idea what I'm doing wrong, would be helpful :)

**Comment by olalonde** [comment]
Oh think I found the issue: https://github.com/pahen/madge/blob/master/lib/parse/es6.js#L41

**Comment by mrjoelkemp** [comment]
My first hunch was that you didn't do `npm i --save detective-es6@1.1.5` and the shinkwrap didn't get updated. Nice find on the import sniff within madge proper.

**Pull request closed without merging**
